// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mindfulness_Hub_V3.Models;

namespace Mindfulness_Hub_V3.Migrations
{
    [DbContext(typeof(mindfulnessContext))]
    partial class mindfulnessContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mindfulness_Hub_V3.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Item_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateLine")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<int>("PriorityId")
                        .HasColumnName("PriorityID");

                    b.Property<int>("StatusId")
                        .HasColumnName("StatusID");

                    b.Property<int>("UserId")
                        .HasColumnName("UserID");

                    b.HasKey("ItemId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Mindfulness_Hub_V3.Models.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PriorityID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("MaxTime")
                        .HasColumnName("Max_Time");

                    b.HasKey("PriorityId");

                    b.ToTable("Priority");
                });

            modelBuilder.Entity("Mindfulness_Hub_V3.Models.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ProfileID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false);

                    b.HasKey("ProfileId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Mindfulness_Hub_V3.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StatusID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("StatusId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Mindfulness_Hub_V3.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("PasswordHash");

                    b.Property<int>("ProfileId")
                        .HasColumnName("ProfileID");

                    b.Property<string>("SecuritySalt");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("UserId");

                    b.HasIndex("ProfileId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Mindfulness_Hub_V3.Models.Item", b =>
                {
                    b.HasOne("Mindfulness_Hub_V3.Models.Priority", "Priority")
                        .WithMany("Item")
                        .HasForeignKey("PriorityId")
                        .HasConstraintName("FK_Item_Priority");

                    b.HasOne("Mindfulness_Hub_V3.Models.Status", "Status")
                        .WithMany("Item")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Item_Status");

                    b.HasOne("Mindfulness_Hub_V3.Models.User", "User")
                        .WithMany("Item")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Item_User1");
                });

            modelBuilder.Entity("Mindfulness_Hub_V3.Models.User", b =>
                {
                    b.HasOne("Mindfulness_Hub_V3.Models.Profile", "Profile")
                        .WithMany("User")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("FK_User_Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
